version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    expose:
      - 27017
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
